language: cpp
sudo: required
dist: xenial # modern Wt

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install --yes gccxml libwt-dev libwthttp-dev
  - sudo pip install cpp-coveralls
  - sudo pip install hererocks
  - sudo pip install pygccxml
  - hererocks here --$LUA --luarocks $LUAROCKS
  - eval $(./here/bin/luarocks path --bin)

install:
  - luarocks make

before_script:
  - sudo apt-get install --yes valgrind
  - luarocks install busted
  - luarocks install luasocket

script:
  - export LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0
  - busted --shuffle --repeat=20 spec/*
  - if [[ "$LUA" != *"luajit"* ]]; then bash .travis/valgrind_test.sh; fi
  - luarocks make CFLAGS="-O0 -g -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"
  - busted spec/*
  # `after_success` section was moved to `script`, because we need to
  # catch errors in automate_bindings.py, but all the errors in
  # `after_success` sections are ignored by the worker.
  - coveralls --include src
  - ./tools/automate_bindings.py --bind /usr/include/Wt/WText
  - luarocks make
