language: cpp

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.3)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install libwt-dev libwthttp-dev
  - sudo pip install cpp-coveralls
  - source .travis/setenv_lua.sh

install:
  - luarocks make

before_script:
  - sudo apt-get install valgrind
  - luarocks install busted
  - luarocks install luasocket

script:
  - export LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0
  - busted
  - if [[ "$LUA" != *"luajit"* ]]; then bash .travis/valgrind_test.sh; fi
  - luarocks make CFLAGS="-O0 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"
  - busted

after_success:
  - coveralls --include src
