language: cpp

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.3)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - sudo apt-get install libwt-dev libwthttp-dev
  - source .travis/setenv_lua.sh

install:
  - luarocks make

before_script:
  - luarocks install busted

script:
  - export LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0
  - busted
