-- luawt, Lua bindings for Wt
-- Copyright (c) 2015-2016 Pavel Dolgov and Boris Nagaev
-- See the LICENSE file for terms of use.

local test = require 'luawt.test'

describe("luawt widgets", function()

    -- List of widgets tests
    it("creates WCalendar", function()
        test.testWidget("WCalendar")
    end)
    it("creates WLineEdit", function()
        test.testWidget("WLineEdit")
    end)
    it("creates WAnchor", function()
        test.testWidget("WAnchor")
    end)
    it("creates WTemplate", function()
        test.testWidget("WTemplate")
    end)
    it("creates WComboBox", function()
        test.testWidget("WComboBox")
    end)
    it("creates WDatePicker", function()
        test.testWidget("WDatePicker")
    end)
    it("creates WTreeNode", function()
        test.testWidget("WTreeNode")
    end)
    it("creates WInPlaceEdit", function()
        test.testWidget("WInPlaceEdit")
    end)
    it("creates WGLWidget", function()
        test.testWidget("WGLWidget")
    end)
    it("creates WVirtualImage", function()
        test.testWidget("WVirtualImage")
    end)
    it("creates WTextArea", function()
        test.testWidget("WTextArea")
    end)
    it("creates WProgressBar", function()
        test.testWidget("WProgressBar")
    end)
    it("creates WFlashObject", function()
        test.testWidget("WFlashObject")
    end)
    it("creates WPanel", function()
        test.testWidget("WPanel")
    end)
    it("creates WScrollArea", function()
        test.testWidget("WScrollArea")
    end)
    it("creates WOverlayLoadingIndicator", function()
        test.testWidget("WOverlayLoadingIndicator")
    end)
    it("creates WTabWidget", function()
        test.testWidget("WTabWidget")
    end)
    it("creates WIconPair", function()
        test.testWidget("WIconPair")
    end)
    it("creates WImage", function()
        test.testWidget("WImage")
    end)
    it("creates WStackedWidget", function()
        test.testWidget("WStackedWidget")
    end)
    it("creates WGoogleMap", function()
        test.testWidget("WGoogleMap")
    end)
    it("creates WCheckBox", function()
        test.testWidget("WCheckBox")
    end)
    it("creates WDefaultLoadingIndicator", function()
        test.testWidget("WDefaultLoadingIndicator")
    end)
    it("creates WSpinBox", function()
        test.testWidget("WSpinBox")
    end)
    it("creates WText", function()
        test.testWidget("WText")
    end)
    it("creates WLabel", function()
        test.testWidget("WLabel")
    end)
    it("creates WGroupBox", function()
        test.testWidget("WGroupBox")
    end)
    it("creates WCompositeWidget", function()
        test.testWidget("WCompositeWidget")
    end)
    it("creates WSlider", function()
        test.testWidget("WSlider")
    end)
    it("creates WTableView", function()
        test.testWidget("WTableView")
    end)
    it("creates WSelectionBox", function()
        test.testWidget("WSelectionBox")
    end)
    it("creates WTreeView", function()
        test.testWidget("WTreeView")
    end)
    it("creates WTreeTableNode", function()
        test.testWidget("WTreeTableNode")
    end)
    it("creates WMenu", function()
        test.testWidget("WMenu")
    end)
    it("creates WTreeTable", function()
        test.testWidget("WTreeTable")
    end)
    it("creates WDoubleSpinBox", function()
        test.testWidget("WDoubleSpinBox")
    end)
    it("creates WFileUpload", function()
        test.testWidget("WFileUpload")
    end)
    it("creates WTree", function()
        test.testWidget("WTree")
    end)
    it("creates WContainerWidget", function()
        test.testWidget("WContainerWidget")
    end)
    it("creates WTable", function()
        test.testWidget("WTable")
    end)
    it("creates WTextEdit", function()
        test.testWidget("WTextEdit")
    end)
    it("creates WPushButton", function()
        test.testWidget("WPushButton")
    end)

end)
