-- luawt, Lua bindings for Wt
-- Copyright (c) 2015-2016 Pavel Dolgov and Boris Nagaev
-- See the LICENSE file for terms of use.

local test = require 'luawt.test'

describe("luawt widgets", function()

    -- List of widgets tests
    it("creates WCalendar", function()
        test.testWidget("WCalendar", true)
    end)
    it("creates WTemplate", function()
        test.testWidget("WTemplate", true)
    end)
    it("creates WTableView", function()
        test.testWidget("WTableView", true)
    end)
    it("creates WContainerWidget", function()
        test.testWidget("WContainerWidget", true)
    end)
    it("creates WGroupBox", function()
        test.testWidget("WGroupBox", true)
    end)
    it("creates WPushButton", function()
        test.testWidget("WPushButton", true)
    end)
    it("creates WProgressBar", function()
        test.testWidget("WProgressBar", true)
    end)
    it("creates WPanel", function()
        test.testWidget("WPanel", true)
    end)
    it("creates WScrollArea", function()
        test.testWidget("WScrollArea", true)
    end)
    it("creates WLineEdit", function()
        test.testWidget("WLineEdit", true)
    end)
    it("creates WComboBox", function()
        test.testWidget("WComboBox", true)
    end)
    it("creates WTable", function()
        test.testWidget("WTable", true)
    end)
    it("creates WDoubleSpinBox", function()
        test.testWidget("WDoubleSpinBox", true)
    end)
    it("creates WTreeTable", function()
        test.testWidget("WTreeTable", true)
    end)
    it("creates WTextEdit", function()
        test.testWidget("WTextEdit", true)
    end)
    it("creates WSpinBox", function()
        test.testWidget("WSpinBox", true)
    end)
    it("creates WDefaultLoadingIndicator", function()
        test.testWidget("WDefaultLoadingIndicator", false)
    end)
    it("creates WPopupMenu", function()
        test.testWidget("WPopupMenu", false)
    end)
    it("creates WAnchor", function()
        test.testWidget("WAnchor", true)
    end)
    it("creates WSplitButton", function()
        test.testWidget("WSplitButton", true)
    end)
    it("creates WVideo", function()
        test.testWidget("WVideo", true)
    end)
    it("creates WToolBar", function()
        test.testWidget("WToolBar", true)
    end)
    it("creates WNavigationBar", function()
        test.testWidget("WNavigationBar", true)
    end)
    it("creates WTreeView", function()
        test.testWidget("WTreeView", true)
    end)
    it("creates WSlider", function()
        test.testWidget("WSlider", true)
    end)
    it("creates WAudio", function()
        test.testWidget("WAudio", true)
    end)
    it("creates WGoogleMap", function()
        test.testWidget("WGoogleMap", true)
    end)
    it("creates WFileUpload", function()
        test.testWidget("WFileUpload", true)
    end)
    it("creates WImage", function()
        test.testWidget("WImage", true)
    end)
    it("creates WCheckBox", function()
        test.testWidget("WCheckBox", true)
    end)
    it("creates WOverlayLoadingIndicator", function()
        test.testWidget("WOverlayLoadingIndicator", false)
    end)
    it("creates WTabWidget", function()
        test.testWidget("WTabWidget", true)
    end)
    it("creates WStackedWidget", function()
        test.testWidget("WStackedWidget", true)
    end)
    it("creates WText", function()
        test.testWidget("WText", true)
    end)
    it("creates WSelectionBox", function()
        test.testWidget("WSelectionBox", true)
    end)
    it("creates WTree", function()
        test.testWidget("WTree", true)
    end)
    it("creates WTextArea", function()
        test.testWidget("WTextArea", true)
    end)
    it("creates WDateEdit", function()
        test.testWidget("WDateEdit", true)
    end)
    it("creates WLabel", function()
        test.testWidget("WLabel", true)
    end)
    it("creates WDatePicker", function()
        test.testWidget("WDatePicker", true)
    end)

end)
